config/routes.rb
Mascotas::Application.routes.draw do |map|
  devise_for :users
  
    resources :publications
    root :to => "publications#index"
    

   

end

app/models/publication.rb
class Publication < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "300x300>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable, :confirmable and :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController

  def index
    @publications = Publication.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @publications }
    end
  end
  
  def new
    @publication = Publication.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @publication }
    end
  end

  def create
    @publication = Publication.new(params[:publication])
    @publication = Publication.create(params[:publication] )

    respond_to do |format|
      if @publication.save
        format.html { redirect_to(@publication, :notice => 'Publication was successfully created.') }
        format.xml  { render :xml => @publication, :status => :created, :location => @invoice }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @publication.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show
    @publication = Publication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @publication }
    end
  end
  
  def edit
    @publication = Publication.find(params[:id])
  end

  def update
    @publication = Publication.find(params[:id])

    respond_to do |format|
      if @publication.update_attributes(params[:publication])
        format.html { redirect_to(@publication, :notice => 'Publication was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @publication.errors, :status => :unprocessable_entity }
      end
    end
  end
  
    def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

	respond_to do |format|
	  format.html { redirect_to(publications_url) }
	  format.xml  { head :ok }
	end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mascotas</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/publications/_form.html.erb
<%= form_for(@publication, :html => { :multipart => true }) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
    <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  
   <div class="field">
    <%= f.file_field :image %><br /> 
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<h1> Listing Publications </h1><table>  <tr>    <th>Title</th>    <th>Description</th>    <th>Date</th>    <th>Imagen</th>    <th></th>    <th></th>    <th></th>  </tr><% @publications.each do |publication| %>  <tr>    <td><%= publication.title %></td>    <td><%= publication.description %></td>    <td><%= publication.date %></td>    <td><%= publication.image_file_name %></td>    <td><%= link_to 'Show', publication %></td>	<td><%= link_to 'Edit', edit_publication_path(publication) %></td>	<td><%= link_to 'Destroy', publication, :confirm => 'Are you sure?', :method => :delete %></td>  </tr><% end %></table><br /><%= link_to 'New Publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render 'form' %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @publication.title %>
</p>


<p>
  <b>Description:</b>
  <%= @publication.description %>
</p>

<p>
  <b>Date:</b>
  <%= @publication.date %>
</p>

  <b>Imagen:</b>
  <%= @publication.image_file_name %>
</p>


<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %> 

<%= image_tag @publication.image.url(:medium) %> 
<%= image_tag @publication.image.url(:thumb) %>